apiVersion: v1
kind: Service
metadata:
  name: inova-backend-service
  namespace: inova
  labels:
    app: inova-backend
spec:
  type: LoadBalancer
  selector:
    app: inova-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP