app_name: inova-research-agent
app_user: "{{ ansible_user }}"
app_group: "{{ ansible_user }}"

app_base_dir: "/home/{{ app_user }}/apps/{{ app_name }}"
app_src_dir: "{{ app_base_dir }}/src_rootless"
app_compose_dir: "{{ app_base_dir }}/deploy"
app_env_path: "{{ app_compose_dir }}/.env"

app_repo_url: "https://github.com/AmrQamhieh/inova-research-agent.git"
app_repo_branch: "develop"

app_port: 8000

db_name: inova_agent
db_user: inova
db_password: "CHANGE_ME_DB_PASSWORD"
db_host: db
db_port: 5432

postgres_image: "docker.io/library/postgres:16-alpine"

db_data_dir: "{{ app_base_dir }}/data/postgres"

required_packages:
  - git
  - firewalld
  - podman
  - python3-pip
  - lvm2

lvm_enabled: false
lvm_device: ""
lvm_vg_name: "appvg"
lvm_lv_name: "postgres_lv"
lvm_lv_size: "5g"
lvm_mount_path: "/srv/postgres-data"
lvm_fs_type: "xfs"

effective_db_data_dir: "{{ lvm_mount_path if lvm_enabled else db_data_dir }}"
openai_model: gpt-4.1-mini